/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: joneschr003 (https://sketchfab.com/joneschr003)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sonic-lost-world-sonic-model-f0fc312eef804b85afecce3d0bcc91e0
Title: Sonic-lost-world-sonic-model
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import scene from '../assets/3d/sonic-lost-world-sonic-model.glb'

function Sonic({currentAnimation, ...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions);
    Object.values(actions).forEach((action) => action.stop())

    if(actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
    
  }, [currentAnimation, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
          <group name="Root">
            <group name="Hemi001">
              <group name="Hemi001_1" />
            </group>
            <group name="Armature" position={[0, 0, 5.169]} scale={234.624}>
              <primitive object={nodes.Armature_rootJoint} />
              <skinnedMesh
                name="Mesh1_0"
                geometry={nodes.Mesh1_0.geometry}
                material={materials.sonic_gm_body}
                skeleton={nodes.Mesh1_0.skeleton}
              />
              <skinnedMesh
                name="Mesh1_1"
                geometry={nodes.Mesh1_1.geometry}
                material={materials.sonic_gm_shoes_red}
                skeleton={nodes.Mesh1_1.skeleton}
              />
              <skinnedMesh
                name="Mesh1_2"
                geometry={nodes.Mesh1_2.geometry}
                material={materials.sonic_gm_cloth}
                skeleton={nodes.Mesh1_2.skeleton}
              />
              <skinnedMesh
                name="Mesh1_3"
                geometry={nodes.Mesh1_3.geometry}
                material={materials.sonic_gm_eyeL}
                skeleton={nodes.Mesh1_3.skeleton}
              />
              <group name="Mesh1" />
            </group>
            <group name="Hemi">
              <group name="Hemi_1" />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Sonic;
